apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web
  labels:
    name: nodejs-web
spec:
# replica set tdk akan dihapus hal ini jika ingin melakukan rollback deployment. defaultnya history replica set adlh 10, kita set 5 replica set saja
  revisionHistoryLimit: 5
  replicas: 3
  selector:
    matchLabels:
      name: nodejs-web
  template:
    metadata:
      name: nodejs-web
      labels:
        name: nodejs-web
    spec:
      containers:
        - name: nodejs-web
          image: khannedy/nodejs-web:2
          ports:
            - containerPort: 3000