apiVersion: v1
kind: Pod
metadata:
  name: nodejs-writer
  labels:
    name: nodejs-writer
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - name: nodejs-writer
      image: khannedy/nodejs-writer
      volumeMounts:
        - mountPath: /app/folder-from-env
          name: html
      env:
      # env var for save berkas into volume. name volume
        - name: HTML_LOCATION
        # directory of volume. if name volume no set so our app will default volume, look images/app.js if !location
          value: /app/folder-from-env