# sources https://github.com/khannedy/belajar-kubernetes/blob/master/templates/pod.yaml

# versi 1
apiVersion: v1

# jenis yg digunakan adlh pod
kind: Pod

# info tmbhn meta data
metadata:
# nama pod
  name: pod-name
spec:
  containers:
  # multiple container
    # container ke 1
    - name: container-name
    # nama image
      image: image-name
      # if need run on particular port
      ports:
        - containerPort: 80
      # container ke 2
    - name: container-name2
    # nama image
      image: image-name2
      # if need run on particular port
      ports:
        - containerPort: 8080