# confi file for make job
# pake batch versi 1
apiVersion: batch/v1
# jenisnya job
kind: Job
metadata:
  name: job-name
  labels:
    label-key1: label-value1
  annotations:
    annotation-key1: annotation-value1
spec:
# completions & parallelism hrs di define if not will default 1 & 1 
  # berapa kali job hrs dijlnkan sampai job-nya complete (job akan berjln 5 kali kemudian berhenti) 
  completions: 5
  # berapa banyak pod yg berjln dlm satu waktu (pd satu waktu akan ada 2 pod yg jalan, pertama 2 pod nyala, selanjutnya 2 pod lagi nyala, terakhir 1 pod lagi akan nyala (karena kita set 5 diatas))
  parallelism: 2
# replica set
  selector:
    matchLabels:
      abel-key1: label-value1
  template:
    metadata:
      name: pod-name
      labels:
        label-key1: label-value1
    spec:
      restartPolicy: Never
      containers:
        - name: container-name
          image: image-name
          ports:
            - containerPort: 80