# config file akan di submit/push to kubernetes master (api kubernetes)
apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-probe-error
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
        # url-nya salah(tdk ada), hanya ada /
          path: /404
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3