apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web
  labels:
    name: nodejs-web
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nodejs-web
  template:
    metadata:
      name: nodejs-web
      labels:
        name: nodejs-web
    spec:
      containers:
        - name: nodejs-web
          image: khannedy/nodejs-web
          ports:
            - containerPort: 3000
          resources:
            requests:
            # karena ada 3 pod (replica=3) maka server bth 1000m x 3 = 3 core
              cpu: 1000m
            # karena ada 3 pod (replica=3) maka server bth 1000Mi x 3= sekitar 3 GB (RAM)
              memory: 1000Mi
            limits:
            # karena ada 3 pod (replica=3) maka server bth 1000m x 3= 3 core untuk limit
              cpu: 1000m
            # karena ada 3 pod (replica=3) maka server bth 1000Mi x 3= sekitar 3 GB (RAM)
              memory: 1000Mi

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-web-service
spec:
  type: NodePort
  selector:
    name: nodejs-web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001