apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: name-stateful
  labels:
    name: name-stateful
spec:
  # https://github.com/kubernetes/kubernetes/issues/69608
  # serviceName used when we want expose statefulset-nya kedlm service jd hrs memasukkan nama service ini, pdhl tanpa membuat service pun statefulset tetap jln
  serviceName: name-stateful-service
  replicas: 3
  # label selector untuk pod
  selector:
    matchLabels:
      name: name-stateful
  # buat volume claim template (template used untuk membuat volume)
  volumeClaimTemplates:
    - metadata:
        name: name-stateful-volume-claim
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
  # template pod (template untuk membuat pod)
  template:
    metadata:
      name: name-stateful
      labels:
        name: name-stateful
    spec:
      containers:
        - name: name-stateful
          image: image/name-stateful
          volumeMounts:
            - mountPath: /app/data
            # nama nya hrs == nama template volume claim
              name: name-stateful-volume-claim