apiVersion: v1
kind: Service
metadata:
  name: service-name
  labels:
    label-key1: label-value1
spec:
# type-nya NodePort, defaultnya ClusterIP
  type: NodePort
  selector:
    label-key1: label-value1
  ports:
    - port: 80
      targetPort: 80
      # tambahkan nodePort, port ini akan diekspos keluar / digunakan oleh node
      nodePort: 32767