apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
# node selector
  nodeSelector:
  # key: value
    gpu: "true"
  containers:
    - name: container-name
      image: image-name
      ports:
        - containerPort: 80